{"version":1,"ops":[{"type":1,"author":{"id":"aa8915ba52969f979af836ca4704fd27e613004f"},"timestamp":1266311415,"metadata":{"github-id":"MDU6SXNzdWUyODQ4NzM5","github-url":"https://github.com/parrot/parrot/issues/531","origin":"github"},"title":"Modify `throw` opcode to pass through pre-configured resume continuation","message":"Presently, the throw opcode creates and sets a resume continuation on the exception being thrown. \n\nSince 'resume' is an attribute of the Exception, throw should check first for a preconfigured continuation, and if one exists should preserve it.\n\n(Of course, if unset it should continue to do what it does.)\n\nOriginally http://trac.parrot.org/parrot/ticket/1448","files":null}]}